/*
 * hello.c
 *
 *  Created on: 2015年6月26日
 *      Author: Administrator
 */

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <elf.h>
#include <fcntl.h>
#include <syslog.h>
#include <string.h>

#define LOG_TAG "[liujinguang]"
//#define LOGD(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, fmt, ##args)

#define LOGD(fmt, args...) printf(fmt, ##args)

//#define LOGD(fmt, args...) syslog(LOG_DEBUG,fmt, ##args)

int InjectEntry(char * param){

    FILE *fp;

    fp = freopen("/root/ljg_log.txt","ab+",stdout);

    char * str = "hello,how are you?\r\n";
    fwrite(str,1,strlen(str),fp);

    openlog(LOG_TAG, LOG_CONS | LOG_PID, 0);
    LOGD("This is a syslog test message generated by program '%s'\n",param);
    
    LOGD("Hook success, pid = %d\n", getpid());
    LOGD("Hello %s\n", param);

    closelog();

    fclose (fp);

    return 0x12345678;
}
